<?php defined("APP") or die("NO DIRECT ACESS !");

$title = "maine - Page";
$header = "Hello Maine";
$text = '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam asperiores atque consequatur consequuntur cupiditate debitis dolores ea eos esse et eum ex excepturi fugit hic impedit in laborum libero minima mollitia nemo quas qui quibusdam, repellendus totam ut voluptatem voluptates. Distinctio, id vitae! Alias dolore, dolorem eius itaque nemo quasi quidem quisquam quo quos vero. Aut beatae neque non numquam odio ullam vel voluptatibus. Dolorem facilis impedit odio officiis optio praesentium quam vel! Aliquid eius unde vitae. A consectetur dolorem esse ex ipsum iusto laudantium molestiae molestias nemo nisi nostrum obcaecati odit pariatur quae, quidem quod repudiandae! Dicta nam, placeat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam asperiores atque consequatur consequuntur cupiditate debitis dolores ea eos esse et eum ex excepturi fugit hic impedit in laborum libero minima mollitia nemo quas qui quibusdam, repellendus totam ut voluptatem voluptates. Distinctio, id vitae! Alias dolore, dolorem eius itaque nemo quasi quidem quisquam quo quos vero. Aut beatae neque non numquam odio ullam vel voluptatibus. Dolorem facilis impedit odio officiis optio praesentium quam vel! Aliquid eius unde vitae. A consectetur dolorem esse ex ipsum iusto laudantium molestiae molestias nemo nisi nostrum obcaecati odit pariatur quae, quidem quod repudiandae! Dicta nam, placeat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam asperiores atque consequatur consequuntur cupiditate debitis dolores ea eos esse et eum ex excepturi fugit hic impedit in laborum libero minima mollitia nemo quas qui quibusdam, repellendus totam ut voluptatem voluptates. Distinctio, id vitae! Alias dolore, dolorem eius itaque nemo quasi quidem quisquam quo quos vero. Aut beatae neque non numquam odio ullam vel voluptatibus. Dolorem facilis impedit odio officiis optio praesentium quam vel! Aliquid eius unde vitae. A consectetur dolorem esse ex ipsum iusto laudantium molestiae molestias nemo nisi nostrum obcaecati odit pariatur quae, quidem quod repudiandae! Dicta nam, placeat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam asperiores atque consequatur consequuntur cupiditate debitis dolores ea eos esse et eum ex excepturi fugit hic impedit in laborum libero minima mollitia nemo quas qui quibusdam, repellendus totam ut voluptatem voluptates. Distinctio, id vitae! Alias dolore, dolorem eius itaque nemo quasi quidem quisquam quo quos vero. Aut beatae neque non numquam odio ullam vel voluptatibus. Dolorem facilis impedit odio officiis optio praesentium quam vel! Aliquid eius unde vitae. A consectetur dolorem esse ex ipsum iusto laudantium molestiae molestias nemo nisi nostrum obcaecati odit pariatur quae, quidem quod repudiandae! Dicta nam, placeat. </p>'

?>